apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: node
  name: node-controller
spec:
  replicas: 2
  selector:
    name: node
  template:
    metadata:
      labels:
        name: node
    spec:
      containers:
      - image: gaffoor/node-from-jenkins
        name: node
        ports:
        - containerPort: 3000
          name: http-server